//
// Created by 27091 on 2026/5/16.
//

#ifndef SIMPLE_NOTEPAD_PROJECT_WORD_FREQUENCY_DIALOG_H
#define SIMPLE_NOTEPAD_PROJECT_WORD_FREQUENCY_DIALOG_H

#endif //SIMPLE_NOTEPAD_PROJECT_WORD_FREQUENCY_DIALOG_H